// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_ribbon_stats
List compute_ribbon_stats(NumericVector x, NumericVector y, IntegerVector group, NumericVector widths);
RcppExport SEXP _fastribbon_compute_ribbon_stats(SEXP xSEXP, SEXP ySEXP, SEXP groupSEXP, SEXP widthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type widths(widthsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ribbon_stats(x, y, group, widths));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastribbon_compute_ribbon_stats", (DL_FUNC) &_fastribbon_compute_ribbon_stats, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastribbon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
