# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
compute_ribbon_stats <- function(x, y, group, widths) {
    .Call(`_fastribbon_compute_ribbon_stats`, x, y, group, widths)
}

